# Shahadah - Declaration of Faith
"Laa ilaha ilia Allah, Muhammad Rasuul Allah". No deity is worthy or has the right of being worshiped but Allah and Muhammad is the messenger of Allah. The first part of the declaration attests to the immortal. Everlasting Oneness and Uniqueness of Almighty Allah. The second part refers to the mortal Muhammad as the messenger of Allah who received revelation (the Quran) through the Angle Gabriel, in stages over a period of 23 years. Muhammad then lived the life of the Quran and taught it to mankind.

## Why
Islam is a complete and practical way of life. The declaration is its foundation and most important pillar on which stand all other beliefs and practices. After declaring the Shahadah, a Muslim must put into practice what he or she declares by the tongue (word) by fulfilling the other pillars and by following the teachings of Prophet Muhammad (peace and blessings of Allah be upon him). The Shahadah is declared in Arabic, in the presence of Muslim witnesses.

## Benefits

Foundation of one becoming, being known and being treated with the rights and
responsibilities of a Muslim by Allah, oneself and others (Muslims and non-Muslims).

## Furthermore

The declaration of faith means that a Muslim believes in the six pillars of faith:

* Belief in Allah, affirming that Allah is the One and Only, Eternal and Absolute, All-Powerful, Perfect and Complete, that He has neither partner, nor son. He is high above any imperfections. No deficiencies or flaws can be attributed to Him. None is like Him. Muslims must love Allah more than anything or anybody, fear Him and put their trust in Him. 
* Belief in His Angels as Perfect beings who always worship Allah and never disobey Him. They are different from people and genies, do not eat or excrete, and have no gender. 
* Belief in His Books many, including Scrolls, Psalms, Torah, Gospel and Quran) 
* Belief in His Messengers, no society was left without a messenger, from Adam, Noah, Abraham, Isaac, Jacob, Joseph, David, Solomon, Ishmael, to Muhammad, the last messenger) 
* Belief in The Day of Judgment, every being will die and will be resurrected on this day and be accountable for all their good and bad deeds while living on earth, for which they will either receive reward (Jannah meaning Heaven) or punishment (Jahannam meaning Hellfire).
* Belief in Destiny and Fate, Muslims have to put their trust in Allah and that everything happens by His will and for their own good, even though by mortal limitations, they may not understand or perceive the wisdom as to why things happen as they do.