# Prayers (Salaah)
This transforms the 1st pillar, declaration of faith by word, into practice by the physical worship of Allah with 5 prayers daily. The prayers and number of rakaa (cycles) are:

* **Fajr** (dawn) - 2 rakaa
* **Dhuhr** (soon after noon) - 4 rakaa
* **Asr** (afternoon) - 4 rakaa
* **Maghrib** (sunset) - 3 rakaa
* **lsha** (early night) - 4 rakaa

To physically worship and glorify Allah; maintain a consciousness of Allah (taqwa); and have a continuous direct link to Allah without intermediary. It is a means to purify the body and soul resulting in Allah's protection, peace with Allah and inner peace and tranquility. It is the first right of Allah from a believer that differentiates Muslims from non-Muslims. Obligatory prayers are performed in Arabic, the language of revelation, individually or in congregation. It is preferable for women to pray at home but mandatory for men to pray in congregation in a mosque otherwise one can pray at any clean place: office, field or school. Proper dress code and cleanliness of body, clothes and place of prayer are prerequisites. Obligatory prayers must be on time and take priority over everything else. Congregational prayers are led by an Imam, normally chosen by the congregation. While praying, Muslims must face Qibla, the direction of Kaaba in Makkah. The prayer is conducted in Arabic with recitations from the Quran. Each prayer cycle consists of standing, bowing, prostrating and sitting. If one cannot pray while standing, one must pray while seated, and if unable to sit, then while resting on the bed.

## Benefits
When performed properly and sincerely, prayers teach a Muslim to be humble before his Creator, especially during prostration.

**The benefits are that it**
Maintains a continuous direct link (hotline) to Allah without intermediary. Cleanse the body and soul of indecency. Protect believers from bad deeds/sins and guide them to good deeds Promote discipline, consciousness and fear of Allah (taqwa), and trust in Allah. Promote sense of belonging, equality and brotherhood in the community. Determine the rhythm of the day with work then a break for prayers. Short meditation/de-stressor sessions promote inner self tranquility Like other physical exercises, prayers increase blood circulation and body flexibility. Bowing and prostration increase blood supply to the brain, improving brain function and memory, and promotes spine suppleness. Electrostatic charges from the atmosphere accumulate in the central nervous system and when over saturated, may cause neck/headaches and muscle spasms. Prostration gets rid of electrostatic charges by discharging and dissipating them out of the body (the way electric appliances require earthing), thus promoting tranquility, peace of mind and soul, and overall muscle relaxation.

## Further
Optional prayers are prescribed before and after obligatory prayers and at other times. These aid the believers to build taqwa and thus bringing them closer to Allah. Voluntary prayers in the darkness of night, especially the last third, carry the biggest merits of optional prayers. Muslims can supplicate in any language and anywhere, except in the toilet.