# Obligatory films (Zakaah)
The Arabic word Zakaah means both purification and growth It is the worship of Allah involving wealth. It is the right of the destitute on the wealthy in society. 2\.5% is paid from wealth one has owned for a whole lunar year if it reaches the nisaab, (the minimum amount on which alms are payable equivalent to the price of 85 grams of gold), or it is paid at the time of harvest for agricultural produce. Zakaah is used to take care of the following needy categories in society: The poor, those who earn less than half of their daily needs. The needy or destitute those who can't work or earn next to nothing Those employed to collect and distribute Zakaah. Wayfarers who have hit hard times though they maybe wealthy back home. Muslim prisoners of war or slaves who want to buy freedom. New Muslims and non-Muslims who are being encouraged to join Islam and whose services will help Islam. Muslims with debt acquired for lawful needs. Supporting welfare organizations looking after the needy. Every Muslim, male or female, must pay 2\.5% of their wealth, for example, gold, silver, money in hand or investments, real estate, or merchandise in their possession for a whole lunar year, if it exceeds the nisaab. Zakaah is also payable on certain kinds of livestock and agricultural produce with different mode of payment. To be valid. Zakaah must be paid when due, must come from the good portion (not cast offs); with spirit of compassion. Those who are not eligible to pay the obligatory Zakaah are encouraged to offer voluntary charity (sadaqah), which is also applicable for those who have to pay Zakaah. Sadaqah is not necessarily monetary but any charitable deed such as a smile, visiting the sick or clearing obstructions on a path.