# Fasting (Sawm)
The Arabic word sawm means abstention. During Ramadhan, the 9th month of the Muslim calendar (Hijrah), Muslims fast from just before dawn to just after sunset. It is in the month of Ramadhan that the Quran was brought down from the 7th to the 1st Heaven, after which the angel Gabriel (Jibril) revealed it to Prophet Muhammad (PBUH) step by step. Fasting is a mental, physical and spiritual worship of Allah, an exercise in self-control and purification. By abstaining from worldly comforts, even for a short time, a fasting Muslim focuses on the purpose of life by being ever conscious of Allah. In the month of Ramadhan, Muslims make an intention to fast for the sake of Allah, and then abstain from food, drink, sexual relations with spouses, smoking and all other prohibited behavior like backbiting, gossip, adultery, oppression etc., from dawn to sunset. The sick, travelers, as well as pregnant, nursing and menstruating women can break the fast and make up equal number of days later in the year when they are healthy and able. The aged and the terminally ill are exempted from fasting but if they can, they have to feed the poor. Fasting is validated by paying Zakat al Fitr (charity of breaking the fast) before the Eid ul Fitr prayers, the festival marking the end of Ramadhan fasting. Abstaining from worldly comforts focuses Muslims on their purpose in life, being constantly aware and conscious of Allah's presence (taqwa). Spiritually, fasting promotes patience, gratitude, self-purification and self-restraint. It makes a Muslim appreciate Allah's bounties, depress pride and maintain humility. It promotes sympathy and generosity towards the poor. Allah is pleased and appreciates that His servant is abstaining from worldly comforts for Him, the reward of which is admission to Heaven through a special gate, Rayyan. Allah rewards every good deed tenfold, but He is much more generous with regards to fasting because only He knows if the Muslim has truly observed the fast. A fasting Muslim rejoices twice while breaking the fast and on the Day of Judgment. The bad-smelling breath of a fasting Muslim is more pleasant to Allah than the fragrance of musk, Gates of hell are closed while gates of Heaven are open, and Satan is chained When a Muslim fasts sincerely for Allah expecting His reward, Allah will forgive him all his past sins, similarly for one who wakes up to sincerely worship Allah on the Night of Power (Lailatul Qadr, which falls in the last ten days of Ramadhan. If a Muslim goes for lesser Hajj (Umrah) during Ramadhan, it is equivalent to going for Hajj. Voluntary worship like voluntary prayers and charity is equivalent to obligatory worship. When fasting is combined with proper nutrition, it promotes health in various ways: Enzymes enter the bloodstream to wash out bacteria, pollutants, damaged and dead cells and metabolic waste, the digestive system gets a rest; cells and tissues are repaired and purified; immune function is enhanced, levels of cholesterol, blood sugar and blood pressure drop, enabling respite to those who suffer these chronic conditions and may improve long-term health, many people are able to permanently break bad habits like smoking and overeating.

## Furthermore
Apart from the obligatory fasting during Ramadhan, there are voluntary fasts that have been prescribed weekly (Monday and Thursday), monthly (13, 14, and 15 of every lunar month), and annually: 2 days of the 1st month of the Hijrah calendar, 6 days of the 10th month of Hijrah, and the first 9 days of the last month of Hijrah The best voluntary fast for those who can, is the fast of Prophet David: on alternate days. Fasting is prohibited on Eid days and lone Fridays.