# Pilgrimage (Hajj)
Hajj is pilgrimage to the Holy places in Makkah and its environs, which is an obligation only for adult Muslims who have the physical and financial ability to make the journey once in a lifetime It Is a form of worship in which a set period of time is devoted, by the pilgrims ritual and performance, to the task of freeing minds and hearts from all worldly concerns. Pilgrims seek to pursue a unique form of universal collective worship of Allah and seek closeness to Him in the one and only location and at the only time chosen by Him. Hajj is a physical, ritual worship which requires money to be fulfilled. Every step of Hajj is a reminder, a sign of submission to Allah, an instructive tool for self-discipline and piety. It serves to cleanse the soul of the pilgrims so that they return home as pure as the day they were born. Behind every aspect of the Hajj is some reflection signifying the Hereafter There are variations to the performance of Hajj depending on whether one first performs Umrah (lesser pilgrimage), rests and then performs Hajj; combines Umrah and Hajj, or having performed Umrah before, is performing just Hajj, which is done only from 8th to 13th of the last month of the Hijrah calendar, called Dhul-Hijjah (month of Hajj). Hajj involves many steps and regulations too numerous to list here, including, but not limited to, intention, wearing special garment (ihram), chanting the talbiyah, moving between Makkah and its environs of Mina, Arafaat and Muzdalifah while performing different prescribed rituals, prayers and supplications, shaving hair for men and a little trim for women, and circumambulation of the Kaabah. Some aspects of the Hajj commemorate Prophet Abraham (peace be upon him), the Father of all later Prophets They signify his obedience to Allah in abandoning his wife and baby Ishmael in the desert, and later his ready obedience to sacrifice Ishmael who also submitted in a matchless obedience to his Creator. These are the rituals of stoning the devil, slaughtering a sacrificial animal, drinking zamzam water and the walk (sayi) between the hills of Safa and Marwa.

## Benefits
Hajj is probably the most physically, emotionally and spiritually demanding journey a Muslim will ever make in a lifetime, but when done properly has great rewards on all levels. Pilgrims experience real Muslim brotherhood in the spirit of unity of purpose. They experience real Muslim equality in spite of their racial and social diversity. Hajj is a profound experience that touches pilgrims to the depths of their souls and changes most of them for the better due to the universal love, brotherhood, unity, and patience. Not everyone is granted the ability to make the Hajj, hence a Muslim is humbled and grateful for the blessing of being one among the chosen few. A pilgrim whose Hajj is accepted, returns home with a clean slate meaning all sins forgiven. Some pilgrims take a lifetime to save enough for the ultimate ambition of going for Hajj, knowing that if their Hajj is accepted, there will be no reward from Allah but Paradise. Furthermore: If one can go for Umrah multiple times, it is advisable they do so, because from one Umrah to the next is expiation for minor sins committed in between. Umrah during Ramadhan is as meritorious as Hajj. There is great merit in facilitating those who are financially unable to carry out this obligation. The close of the Hajj is marked by a festival, the Eid ul ­Adha (festival of sacrifice), which is celebrated with animal sacrifice, prayers and exchange of gifts in Muslim communities everywhere. Eid ul­ Adha and Eid ul Fitr, a festive day celebrating the end of Ramadhan, are the two festivals of the Islamic calendar.